### ISSUE TITLE
Can't open diagram with a stalled(?) comment node

### ISSUE THREAD

**Issue by actionless** [gaphor/gaphor#286]
### I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Loading stucks with the exception pritned:
```python
gaphor.storage.storage INFO Loading file deployment_diagram.gaphor
gaphor.storage.parser ERROR File corrupted, remove element 8cef44be-7376-11ea-80af-e4f89cae6ece and try again
NoneType: None
gaphor.storage.storage INFO Read 140 elements from file
gaphor.storage.storage WARNING file b'/home/lie/projects/test/deployment_diagram.gaphor' could not be loaded (module 'gaphor.UML' has no attribute 'CommentItem')
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gaphor/misc/gidlethread.py", line 127, in __generator_executer
    result = next(self._generator)
  File "/usr/lib/python3.8/site-packages/gaphor/storage/storage.py", line 311, in load_generator
    for percentage in load_elements_generator(
  File "/usr/lib/python3.8/site-packages/gaphor/storage/storage.py", line 182, in load_elements_generator
    yield from _load_elements_and_canvasitems(
  File "/usr/lib/python3.8/site-packages/gaphor/storage/storage.py", line 222, in _load_elements_and_canvasitems
    cls = getattr(UML, elem.type)
AttributeError: module 'gaphor.UML' has no attribute 'CommentItem'
```

### Minimal reproduction of the problem with instructions
1) create a diagram with comment element (probably it was due to adding and then removing the comment node, see example files attached in one of the comments below)
2) save it
3) close the Gaphor app
4) reopen the diagram again

### System Information
OS:
- [x] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

**Comment by actionless** [comment]
while looking further i found weird comment item in the .gaphor diagram file:

```diff
-<CommentItem id="8cef44be-7376-11ea-80af-e4f89cae6ece">
-<matrix>
-<val>(1.0, 0.0, 0.0, 1.0, 135.90929412841797, 720.6576538085938)</val>
-</matrix>
-<width>
-<val>100.0</val>
-</width>
-<height>
-<val>94.0</val>
-</height>
-<subject>
-<ref refid="8cef3992-7376-11ea-80af-e4f89cae6ece"/>
-</subject>
-</CommentItem>
```

and removing it helped to open the file

(further saving and re-opening works fine again)

**Comment by actionless** [comment]
however now when i'm closing the file i'm getting these exceptions (however the changes seems to be saved correctly):

```
gaphor.application INFO Shutting down service event_manager                                                                                                        [16/2297]
gaphor.application INFO Shutting down service diagram_export
gaphor.application INFO Shutting down service elementeditor
gaphor.application INFO Shutting down service xmi_export
gaphor.application INFO Shutting down service properties
gaphor.application INFO Shutting down service recent_files
gaphor.application INFO Shutting down service element_factory
gaphor.UML.properties ERROR Removing <gaphor.UML.uml2.Node object at 0x7f8218a07fa0> from list [<gaphor.UML.uml2.Artifact object at 0x7f8218a0d100>, <gaphor.UML.uml2.Artifa
ct object at 0x7f8218a0d220>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0d2e0>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0d3a0>, <gaphor.UML.uml2.Actor object at 0x7
f8218a0d400>, <gaphor.UML.uml2.Actor object at 0x7f8218a0d940>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0db80>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0dc10>, <g
aphor.UML.uml2.Artifact object at 0x7f8218a0f310>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f4f0>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f5b0>, <gaphor.UML.uml
2.Artifact object at 0x7f8218a0f670>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0fbb0>] failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 473, in _del_many
    items.remove(value)
ValueError: list.remove(x): x not in list
gaphor.UML.properties ERROR Removing <gaphor.UML.uml2.Node object at 0x7f8218a0d9a0> from list [<gaphor.UML.uml2.Artifact object at 0x7f8218a0db80>, <gaphor.UML.uml2.Artifa
ct object at 0x7f8218a0dc10>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f310>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f4f0>, <gaphor.UML.uml2.Artifact object at
0x7f8218a0f5b0>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f670>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0fbb0>] failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 473, in _del_many
    items.remove(value)
ValueError: list.remove(x): x not in list
gaphor.UML.properties ERROR Removing <gaphor.UML.uml2.Node object at 0x7f8218a0da00> from list [<gaphor.UML.uml2.Artifact object at 0x7f8218a0db80>, <gaphor.UML.uml2.Artifa
ct object at 0x7f8218a0dc10>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f310>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f4f0>, <gaphor.UML.uml2.Artifact object at
0x7f8218a0f5b0>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f670>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0fbb0>] failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 473, in _del_many
    items.remove(value)
ValueError: list.remove(x): x not in list
gaphor.UML.properties ERROR Removing <gaphor.UML.uml2.Node object at 0x7f8218a0da60> from list [<gaphor.UML.uml2.Artifact object at 0x7f8218a0db80>, <gaphor.UML.uml2.Artifa
ct object at 0x7f8218a0dc10>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f310>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f4f0>, <gaphor.UML.uml2.Artifact object at
0x7f8218a0f5b0>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0f670>, <gaphor.UML.uml2.Artifact object at 0x7f8218a0fbb0>] failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 473, in _del_many
    items.remove(value)
ValueError: list.remove(x): x not in list
```

**Comment by actionless** [comment]
the full stacktrace for the above:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gaphor/ui/mainwindow.py", line 251, in _on_window_delete
    self.event_manager.handle(SessionShutdownRequested(self))
  File "/usr/lib/python3.8/site-packages/gaphor/services/eventmanager.py", line 65, in handle
    self._events.handle(e)
  File "/usr/lib/python3.8/site-packages/generic/event.py", line 64, in handle
    handler(event)
  File "/usr/lib/python3.8/site-packages/gaphor/ui/filemanager.py", line 273, in _on_session_shutdown_request
    confirm_shutdown()
  File "/usr/lib/python3.8/site-packages/gaphor/ui/filemanager.py", line 241, in confirm_shutdown
    self.event_manager.handle(SessionShutdown(self))
  File "/usr/lib/python3.8/site-packages/gaphor/services/eventmanager.py", line 65, in handle
    self._events.handle(e)
  File "/usr/lib/python3.8/site-packages/generic/event.py", line 64, in handle
    handler(event)
  File "/usr/lib/python3.8/site-packages/gaphor/ui/__init__.py", line 77, in on_session_shutdown
    application.shutdown_session(session)
  File "/usr/lib/python3.8/site-packages/gaphor/application.py", line 85, in shutdown_session
    session.shutdown()
  File "/usr/lib/python3.8/site-packages/gaphor/application.py", line 160, in shutdown
    self.shutdown_service(name)
  File "/usr/lib/python3.8/site-packages/gaphor/application.py", line 173, in shutdown_service
    srv.shutdown()
  File "/usr/lib/python3.8/site-packages/gaphor/UML/elementfactory.py", line 54, in shutdown
    self.flush()
  File "/usr/lib/python3.8/site-packages/gaphor/UML/elementfactory.py", line 179, in flush
    element.unlink()
  File "/usr/lib/python3.8/site-packages/gaphor/UML/element.py", line 129, in unlink
    prop.unlink(self)
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 501, in unlink
    self.__delete__(obj, value)
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 147, in __delete__
    self._del(obj, value)
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 446, in _del
    self._del_many(obj, value, from_opposite, do_notify)
  File "/usr/lib/python3.8/site-packages/gaphor/UML/properties.py", line 473, in _del_many
    items.remove(value)
ValueError: list.remove(x): x not in list
```

**Comment by actionless** [comment]
ah, and sorry for not uploading the document which causing the issue -- it have some proprietary information, i'll try to replace it without breaking the reproducibility of the problem

**Comment by actionless** [comment]
[deployment_diagram_bak_original_bug.gaphor.txt](https://github.com/gaphor/gaphor/files/4411621/deployment_diagram_bak_original_bug.gaphor.txt)

[deployment_diagram_bak_after_removing_commentitem.gaphor.txt](https://github.com/gaphor/gaphor/files/4411622/deployment_diagram_bak_after_removing_commentitem.gaphor.txt)

**Comment by danyeaw** [comment]
@actionless Thanks for the bug report! I can reproduce that your original model stops Gaphor from loading. I am using the latest master version after #280 was merged, and I wasn't able to recreate this while adding a comment and saving and reopening the model.

Would you mind trying this latest version also, or provide some more detailed steps of how I can reproduce it? Thanks!

**Comment by actionless** [comment]
but how can i fix already existing document?

**Comment by amolenaar** [comment]
I notice that the `CommentItem` you point out is not related to a diagram. That should not have happened. The The id of the comment item (`8cef44be-7376-11ea-80af-e4f89cae6ece`) is also used for a properly placed comment (line 780 in the original model). There are 2 elements in the model with the same Id, which is not to be expected.

It looks to me the fix you did (removing the `<CommentItem ...>` node, is the right thing. I'm curious how it ended up there, though.

With regards to the errors while shutting down (closing a window). These are not a problem. The service is trying to cleanly tear down itself (remove all model elements). I'll have a look if the errors are necessary. I suppose not, though.

**Comment by actionless** [comment]
>  There are 2 elements in the model with the same Id

i think that happened after
1) i've created an element
2) cloned that element
3) removed the original (while clone still used on the diagram)

**Comment by amolenaar** [comment]
I suspect the copy/paste functionality. 

This stuff is not stable enough. 

See #274

**Comment by actionless** [comment]
when copy-pasting nested elements all children getting detached from their parents

**Comment by amolenaar** [comment]
That's also an issue, indeed.

**Comment by amolenaar** [comment]
I fixed the detaching issue in #305. Also I expect it will also prevent the issue with the `CommentItem` from happening again.

**Comment by actionless** [comment]
unfortunately copy-paste of nested models is still not fully working with the diagram attached in one of the messages above

result is better than previously (when all the elements were getting disconnected), but now still some of the elements got disjoined:

![2020-05-10--1589077702_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/81489580-51d68c00-9277-11ea-824c-a999d3a3d117.png)


![2020-05-10--1589077708_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/81489559-189e1c00-9277-11ea-80a1-e3a0afe63953.png)

**Comment by amolenaar** [comment]
Thanks for catching this. I forgot to add some test cases for this scenario. 

I’m on it!

**Comment by actionless** [comment]
thanks a lot for your work, hope some day i could replace VisualParadigmCE with it :)

i think the only remaining thing i am missing is colors and colorthemes, however the colorthemes idea gets a bit scary implementation-wise when i am trying to imagine how to do it properly (ie with CSS or CSS-ish kind of selectors) -- because i'm afraid what trying to do it simple from the beginning would lead to encomplication during the time to extent when that custom style-description language cost is bigger than supporting real CSS

**Comment by amolenaar** [comment]
I think just providing colors for nodes (background/lines/text) is a better starting point. With GTK palettes you can set a default palette. With color themes there're so many variantions (e.g. colors of nested nodes).

WRT copy/paste I think I need to cases:
- copy elements that are grouped in another (parent) element (Node)
- copy elements together with their parent element.

Thanks so much for your constructive feedback!

**Comment by actionless** [comment]
> I think just providing colors for nodes (background/lines/text) is a better starting point. With GTK palettes you can set a default palette. With color themes there're so many variantions (e.g. colors of nested nodes).

my point what after having just bg/line/text people would ask for more, and that simple syntax will be growing and growing until will turn into some incomplete brand new programming language :)

**Comment by actionless** [comment]
even for easy start still css could be used ie,

```
* {
   border-color: red;
   text-color: blue;
   background-color: green;
}
```

and parsed in some naive way, but next grow gradually into real CSS support

**Comment by amolenaar** [comment]
Let's continue the discussion on theming in #284.
